### ISSUE TITLE
Support build ^1.0.0

### ISSUE THREAD

**Issue by amatveiakin** [MikeMitterer/dart-git_version#3]
My project doesn't compile with git_version. Error message:

    Because git_version >=0.3.0 depends on build ^0.12.0
    and source_gen 0.9.5 depends on build ^1.0.0,
    git_version >=0.3.0 is incompatible with source_gen 0.9.5.

Is it possible to support newer versions of `build` package?

**Comment by MikeMitterer** [comment]
Sorry but I'm completely into TS now. I haven't even installed Dart anymore on my PC.
